apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-master
  labels:
    app: redis        
spec: # spec do deployment
  selector: # selector utilizado para criar o serice
    matchLabels:
      app: redis
  replicas: 1
  template: # referente ao POD
    metadata:
      labels:
        app: redis
        role: master
    spec: # spec do POD
      containers:
      - name: master
        image: redis        
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata: 
  name: redis-service
  labels:
        app: redis-service
        role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector: 
    app: redis
    role: master